Rajor_Project_mvc/Models/Catagory.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace Rajor_Project_mvc.Models
{
    public class Catagory
    {
        [Key]
        public int Id { get; set; }
        [Required]
        [DisplayName("Catagory Name")]
        [MaxLength(30)]
        public string Name { get; set; }
        [DisplayName("Display Order")]
        [Range(0,100, ErrorMessage ="DisplayOrder must be between 1 to 100")]
        public int DisplayOrder { get; set; }
    }
}

Rajor_Project_mvc/Models/ErrorViewModel.cs
namespace Rajor_Project_mvc.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Rajor_Project_mvc/Controllers/CatagoryController.cs
using Microsoft.AspNetCore.Mvc;
using Rajor_Project_mvc.Data;
using Rajor_Project_mvc.Models;

namespace Rajor_Project_mvc.Controllers
{
    public class CatagoryController : Controller
    {
        private readonly ApplicationDbContext _db;
        public CatagoryController(ApplicationDbContext db)
        {
            _db = db;
        }
        // GET: /<controller>/
        public IActionResult Index()
        {
            List<Catagory> result = _db.Catagories.ToList();
            return View(result);
        }
        
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(Catagory obj)
        {
            if (ModelState.IsValid)
            {
                var catagoryObj = _db.Catagories.Add(obj);
                _db.SaveChanges();
                TempData["success"] = "Catagory created successfully";
                return RedirectToAction("Index");
            }
            //if the validation fails stay at the current page
           return View();
        }

        public IActionResult Edit(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            Catagory obj = _db.Catagories.Find(id);

            if (obj == null)
            {
                return NotFound();
            }
            return View(obj);
        }
        [HttpPost]
        public IActionResult Edit(Catagory obj)
        {
            if(ModelState.IsValid)
            {
                _db.Catagories.Update(obj);
                _db.SaveChanges();
                TempData["update"] = "Catagory updated successfully";
                return RedirectToAction("Index");
            }
            return View();
        }

        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            Catagory obj = _db.Catagories.Find(id);

            if (obj == null)
            {
                return NotFound();
            }
            return View(obj);
        }
        [HttpPost, ActionName("Delete")]
        public IActionResult DeletePost(int? id)
        {
            if (ModelState.IsValid)
            {
                var obj = _db.Catagories.Find(id);
                _db.Remove(obj);
                _db.SaveChanges();
                TempData["delete"] = "Catagory deleted successfully";
                return RedirectToAction("Index");
            }
            return View();
        }
    }
}

Rajor_Project_mvc/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Rajor_Project_mvc.Models;
using System.Diagnostics;

namespace Rajor_Project_mvc.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Rajor_Project_mvc/Views/Catagory/Create.cshtml
@model Catagory


<form method="post">
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary">Create Category</h2>
            <hr />
        </div>
        <div class="mb-3 row p-1">
            <label asp-for="Name" class="p-0">Category Name</label>
            <input asp-for="Name" type="text" class="form-control" />
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
        <div class="mb-3 row p-1">
            <label asp-for="DisplayOrder" class="p-0">Display Order</label>
            <input asp-for="DisplayOrder" type="text" class="form-control"/>
            <span asp-validation-for="DisplayOrder" class="text-danger"></span>
        </div>

        <div class="row">
            <div class="col-6 col-md-3">
                <button asp-controller="Catagory" asp-action="Create" type="submit" class="btn btn-primary form-control">Create</button>
            </div>
            <div class="col-6 col-md-3">
                <a asp-controller="Catagory" asp-action="Index" class="btn btn-secondary border  form-control">
                    Back to List
                </a>
            </div>
        </div>
    </div>
</form>

@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

Rajor_Project_mvc/Views/Catagory/Delete.cshtml
@model Catagory


<form method="post">
    <input asp-for="Id" hidden />
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary">Delete Category</h2>
            <hr />
        </div>
        <div class="mb-3 row p-1">
            <label asp-for="Name" class="p-0">Category Name</label>
            <input asp-for="Name" type="text" class="form-control" />
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
        <div class="mb-3 row p-1">
            <label asp-for="DisplayOrder" class="p-0">Display Order</label>
            <input asp-for="DisplayOrder" type="text" class="form-control" />
            <span asp-validation-for="DisplayOrder" class="text-danger"></span>
        </div>

        <div class="row">
            <div class="col-6 col-md-3">
                <button asp-controller="Catagory" asp-action="Delete" type="submit" class="btn btn-danger form-control">Delete</button>
            </div>
            <div class="col-6 col-md-3">
                <a asp-controller="Catagory" asp-action="Index" class="btn btn-secondary border  form-control">
                    Back to List
                </a>
            </div>
        </div>
    </div>
</form>

@* partial view is used to apply the validation at the client side *@
@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

Rajor_Project_mvc/Views/Catagory/Edit.cshtml
@model Catagory


<form method="post">
    <input asp-for="Id" hidden />
    <div class="border p-3 mt-4">
        <div class="row pb-2">
            <h2 class="text-primary">Edit Category</h2>
            <hr />
        </div>
        <div class="mb-3 row p-1">
            <label asp-for="Name" class="p-0">Category Name</label>
            <input asp-for="Name" type="text" class="form-control" />
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>
        <div class="mb-3 row p-1">
            <label asp-for="DisplayOrder" class="p-0">Display Order</label>
            <input asp-for="DisplayOrder" type="text" class="form-control" />
            <span asp-validation-for="DisplayOrder" class="text-danger"></span>
        </div>

        <div class="row">
            <div class="col-6 col-md-3">
                <button asp-controller="Catagory" asp-action="Edit" type="submit" class="btn btn-primary form-control">Update</button>
            </div>
            <div class="col-6 col-md-3">
                <a asp-controller="Catagory" asp-action="Index" class="btn btn-secondary border  form-control">
                    Back to List
                </a>
            </div>
        </div>
    </div>
</form>

@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

Rajor_Project_mvc/Views/Catagory/Index.cshtml
@model List<Catagory>

<partial name="_Notification" />

<div class="container">
    <div class="row pt-4 pb-2">
        <div class="col-6">
            <h1 class="text-primary">Catagory List</h1>
        </div>
        <div class="col-6 text-end">
            <a asp-controller="Catagory" asp-action="Create" class="btn btn-primary">
                <i class="bi bi-plus-circle-fill"></i> 
                Create Catagory</a>
        </div>
    </div>
</div>

<table class="table table-bordered table-striped">
    <thead>
    <tr>
        <th>
            Catagory Name
        </th>
        <th>
            Display Order
        </th>
    </tr>
    </thead>
    <tbody>
        @foreach(var obj in Model)
        {

        <tr>
            <td>
                @obj.Name
            </td>
            <td>
                @obj.DisplayOrder
                    
            </td>
            <td>
                <div class="w-75 btn-group" role="group">
                        <a asp-controller="Catagory" asp-action="Edit" asp-route-id="@obj.Id" class="btn btn-primary mx-2"><i class="bi bi-pencil-square"></i></a>
                        <a asp-controller="Catagory" asp-action="Delete" asp-route-id="@obj.Id" class="btn btn-danger mx-2"><i class="bi bi-trash"></i></a>
                </div>
            </td>    
        </tr>
        }
    </tbody>
</table>

Rajor_Project_mvc/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Rajor_Project_mvc/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Rajor_Project_mvc</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css">
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" />
    <link rel="stylesheet" href="~/Rajor_Project_mvc.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-primary border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Rajor_Project_mvc</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Catagory" asp-action="Index">Catagory</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-white bg-primary">
        <div class="container">
            &copy; 2023 - Rajor_Project_mvc - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Rajor_Project_mvc/Views/Shared/_Notification.cshtml
@if(TempData["success"]!=null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    
    <script type="text/javascript">
        toastr.success('@TempData["success"]')
    </script>
}
@if (TempData["error"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>

    <script type="text/javascript">
        toastr.error('@TempData["error"]')
    </script>
}
@if (TempData["update"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>

    <script type="text/javascript">
        toastr.success('@TempData["update"]')
    </script>
}
@if (TempData["delete"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>

    <script type="text/javascript">
        toastr.success('@TempData["delete"]')
    </script>
}